version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    prefix: "ci: "
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    prefix: "bump: "
