name: Continuous deployment

on:
    schedule:
        - cron: '0 0 * * 5,1' # Friday and Monday at midnight

jobs:
    chromatic:
        runs-on: ubuntu-latest
        steps:
            # 👇 Version 2 of the action
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # 👈 Required to retrieve git history
            - name: Install dependencies
              run: npx pnpm i
              # 👇 Adds Chromatic as a step in the workflow
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              # Options required to the GitHub Chromatic Action
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  # 👇 Chromatic projectToken, refer to the manage page to obtain it.
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
